name: Temporary export current JAR

on:
  push:
    branches: [main]
    paths: [.github/workflows/temp-export-current-jar.yml]

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: current-nso-jar
          path: Nso_Offline_By_h0901.jar
          if-no-files-found: error
